### ISSUE TITLE
Failed to load cookie file from cookie: No such file or directory

### ISSUE THREAD

**Issue by tjorim** [home-assistant/audio#10]
Home Assistant Supervised on Debian server
HA: 0.106.5
Supervisor: 209

```
20-03-10 11:10:16 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
Failed to load cookie file from cookie: No such file or directory
```

**Comment by frenck** [comment]
Fixed in #5

**Comment by tjorim** [comment]
Good! Searched for it but it's kinda hard now issues are reported everywhere 😅

**Comment by harryd100** [comment]
Still there in supervisor 214/107.7

**Comment by andriej** [comment]
@frenck still here at supervisor 214 / 107.7 HA

**Comment by TheDK** [comment]
Still there in supervisor 214/107.7

**Comment by andriej** [comment]
@frenck reopen pls, I confirm it's still in latest:
`20-04-14 09:36:02 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
Failed to load cookie file from cookie: No such file or directory`

supervisor 217/0.108.3

**Comment by DDomnick** [comment]
20-04-14 07:31:52 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
Failed to load cookie file from cookie: No such file or directory

**Comment by HA-TB303** [comment]
20-04-22 18:54:43 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
Failed to load cookie file from cookie: No such file or directory

**Comment by ThomYoung** [comment]
Getting this too.
Supervisor 219
20-04-23 12:24:22 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
Failed to load cookie file from cookie: No such file or directory

**Comment by Otitori** [comment]
Snap, me too
Supervisor 219
0.108.9
20-04-25 01:26:16 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
Failed to load cookie file from cookie: No such file or directory

**Comment by Jai5-lang** [comment]
Same issue here on Supervisor 219

20-04-28 08:32:24 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
Failed to load cookie file from cookie: No such file or directory

**Comment by DarwinData** [comment]
Issue still in Supervisor 220
`20-05-03 12:52:23 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
Failed to load cookie file from cookie: No such file or directory
`

**Comment by mattaran** [comment]
Issue still exists in Supervisor 222 with HassOS 3.13

`20-05-13 16:00:20 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
Failed to load cookie file from cookie: No such file or directory`

**Comment by khkremer** [comment]
The issue still exists with supervisor 225 and HassOS 4.8:

20-06-01 22:20:46 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
Failed to load cookie file from cookie: No such file or directory

**Comment by bruert** [comment]
The issue still exists with supervisor 227 and HassOS 4.8:

20-06-04 22:19:46 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
Failed to load cookie file from cookie: No such file or directory

**Comment by mkanet** [comment]
I'm seeing the same thing on supervisor 227 and HassOS 4.10

**Comment by donmueang** [comment]
20-07-02 20:30:38 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
Failed to load cookie file from cookie: No such file or directory

Home Assistant Core 0.112.1

System Health:
docker_version | 19.03.8
hassio | true
host_os | HassOS 4.10
installation_type | Home Assistant
os_name | Linux
os_version | 5.4.44
python_version | 3.7.7
supervisor | 228
version | 0.111.4

**Comment by mr-sneezy** [comment]
Ditto..
20-07-03 23:04:15 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
Failed to load cookie file from cookie: No such file or directory
Super 228. HassOS 4.10.

**Comment by Otitori** [comment]
Same issue
20-07-06 20:38:12 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
Failed to load cookie file from cookie: No such file or directory

arch | x86_64
chassis | desktop
dev | false
docker | true
docker_version | 19.03.4
hassio | true
host_os | Ubuntu 18.04.3 LTS
installation_type | Home Assistant Supervised
os_name | Linux
os_version | 4.15.0-106-generic
python_version | 3.7.7
supervisor | 228
timezone | Pacific/Auckland
version | 0.112.1
virtualenv | false

**Comment by malkie-hass** [comment]
Me too.
Hass OS 4.10 Supervisor 228 on RPI 4

**Comment by cmatte** [comment]
Hass OS 4.11 Supervisor 228 shows the same behavior.

20-07-11 16:58:29 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
Failed to load cookie file from cookie: No such file or directory

**Comment by OldUncleMike** [comment]
Supervisor 229 shows same error. RPI 4

From what I can see PulseAudio has been creating this error since 2013 in Fedora through 2019 without a fix.

"When pulseaudio starts it's trying to read the files
~/.config/pulse/cookie"

I'm guessing a fix is not likely to happen soon, or even if it is worth pursuing.

**Comment by prle77** [comment]
Supervisor 240 RPI4 same error
20-09-06 23:33:14 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
Failed to load cookie file from cookie: No such file or directory
Operating system
HassOS 4.12

**Comment by rob1303-hub** [comment]
Supervisor: 245
Operating system: HassOS 5.2
RPI4 4gb
20-09-17 22:07:28 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
Failed to load cookie file from cookie: No such file or directory

**Comment by j55marshall** [comment]
same here any resolutions to this?

**Comment by mlb6** [comment]
Same issue here while booting Home Assistant for the first time. @frenck This is issue should probably be re-opened. It seems quite critical as new HA user will get this issue on their first experience with HA.
RPI4 4GB

**Comment by frenck** [comment]
It is no problem and not an issue. Furthermore, a lot of issues opened for this and closed again, also no need to tag people.
