### ISSUE TITLE
RPi4 missing Audio devices after 0.106.5 upgrade

### ISSUE THREAD

**Issue by Maco65** [home-assistant/audio#7]
## The problem

After upgrade to 0.106.5 when started Spotify add-on the sound is sort of corrupted and not possible to listed.
When checking on the system I have discovered that on Supervisor/SYSTEM/HARDWARE there is the following information about audio hardware:
audio:
    0:
        name: bcm2835_alsa - bcm2835 ALSA
        type: ALSA
        devices:
            [object Object]
            [object Object]
            [object Object]

And before there were specific names where now I see [object Object].
This might be a reason why the sound is not played properly.
I do not have any other device/software where can use Audio system.

## Environment

Home Assistant frontend: Developer tools -> Info:
Supervisor version 208,
Hostname | hassio
System | HassOS 3.11
Deployment | production

- Home Assistant release with the issue: 0.106.5
- Last working Home Assistant release (if known): 0.106.3 or 0.106.4 - I don't remember
- Operating environment (Hass.io/Docker/Windows/etc.): Hassio
- Integration causing this issue: Spotify Add-on
- Link to integration documentation on our website: 

## Problem-relevant `configuration.yaml`

  There is nothing specific for this Spotify add-on on configuration file
```yaml

```

## Traceback/Error logs

There seem to be no errors (or I did not check well) as in general Sound is produced but it is not possible to listed as there are distrotions (like wrong codec or sound going from "outer space" ;)
```txt

```

## Additional information
This issue was also reported on Spotify Add-on: https://github.com/hassio-addons/addon-spotify-connect/issues/42

Update 7.3.2020
Came to the idea of testing this with  "USB audio card". Plugged-in and I see now in Hardware the following:
audio:
    0:
        name: bcm2835_alsa - bcm2835 ALSA
        type: ALSA
        devices:
            [object Object]
            [object Object]
            [object Object]
    1:
        name: USB-Audio - C-Media USB Headphone Set
        type: Set
        devices:
            [object Object]
            [object Object]

So, also "object Obvject" is created fro USB card while I woudl expect something more meaningfull.
And in Spotify Add-on in the "Output secion" it seems to be not visible, there is only two line to select: "Deafult" and "Built-in Audio Digital Stereo (IEC958)"

**Comment by springstan** [comment]
@frenck Okay good to know ✌

**Comment by Maco65** [comment]
I have update the issue with some simple test results of putting external audio USB card. This card is visible in Hassio Hardware but not visible to Spotify Add-on.

**Comment by pvizeli** [comment]
Do you see it after `ha audio reload`?

**Comment by Maco65** [comment]
@pvizeli , I cannot execute "ha audio reload" - if it shoudl be done on terminal I am getting "Error: unknown command "audio" ofr ha"
When I do "ha hardware audio" I am getting:
``` audio:
  input: {}
  output:
    alsa_output.0.iec958-stereo: Built-in Audio Digital Stereo (IEC958)```

So it looks that USB card is not visible in ha ?
I did restart hass already - no change :(

**Comment by pvizeli** [comment]
You need to update your terminal add-on, so you have access to the new `ha audio` function like on the log.

**Comment by Maco65** [comment]
I have noticed today new release "HassOS Release-3 build 12 (Stable)" and updated my system. After that Spotify add-on started to work normally on external USB sound card ! :)
Then I wanted to test it on default RPi device. Have changed the output in the Add-on configuration and from that moment Spotify add-on connection is grayed in other Spotify apps (both on laptop in the was Wifi and on iPhone on the same WiFi). I ahve tried removing the external USB card, reloading, restarting, rebooting, uninstalling the add-on and installing again - no luck :( 
Home Asisstant device is all the time gray as seen below:
![obraz](https://user-images.githubusercontent.com/18126641/76143897-6762e600-607b-11ea-8cb9-55e5ac8c1555.png)

restared laptop does not help :(

**Comment by Maco65** [comment]
@pvizeli - thanks. I updated terminal and run the command:```
~ $ ha audio reload
Command completed successfully.

No change. The same [object Object] name devices on Supervisor/SYSTEM/HARDWARE.
And as decribed above now I cannot even select this device from another Spotify instance.

**Comment by wackyshan** [comment]
I am facing the same issue with audio distortion while still running on Home Assistant Version 0.106.2. 
Have executed ha audio reload

```
~ $ ha audio reload
Command completed successfully.
```'
No change even after a restart of Home assistant.

**Comment by adamaze** [comment]
just wanted to chime in and say that i think im having the same issue, but it is not using HassOS. im on a Pi 4, and i installed hassio on top of raspbian. if there is anything i can do to help troubleshoot. let me know.

**Comment by pvizeli** [comment]
You can use `pactl` and `ha audio logs` for troubleshooting

**Comment by Maco65** [comment]
@pvizeli when I use ```pactl``` I am getting ```` No valid command specified. ````
when I use ``` ha audio log ``` I am getting the following log:
````
I: [pulseaudio] client.c: Created 14 "Native client (UNIX socket client)"       
I: [pulseaudio] protocol-native.c: Client authenticated anonymously.            
D: [pulseaudio] protocol-native.c: Protocol version: remote 33, local 33        
D: [pulseaudio] protocol-native.c: SHM possible: no                             
D: [pulseaudio] protocol-native.c: Negotiated SHM: no                           
D: [pulseaudio] protocol-native.c: Disabling srbchannel, reason: No SHM support 
I: [pulseaudio] client.c: Freed 14 "supervisor"                                 
I: [pulseaudio] protocol-native.c: Connection died.                             
I: [pulseaudio] client.c: Created 15 "Native client (UNIX socket client)"       
I: [pulseaudio] protocol-native.c: Client authenticated anonymously.            
D: [pulseaudio] protocol-native.c: Protocol version: remote 33, local 33        
D: [pulseaudio] protocol-native.c: SHM possible: no                             
D: [pulseaudio] protocol-native.c: Negotiated SHM: no                           
D: [pulseaudio] protocol-native.c: Disabling srbchannel, reason: No SHM support 
I: [pulseaudio] client.c: Freed 15 "supervisor"                                 
I: [pulseaudio] protocol-native.c: Connection died.                             
I: [pulseaudio] client.c: Created 16 "Native client (UNIX socket client)"       
I: [pulseaudio] protocol-native.c: Client authenticated anonymously.            
D: [pulseaudio] protocol-native.c: Protocol version: remote 33, local 33        
D: [pulseaudio] protocol-native.c: SHM possible: no                             
D: [pulseaudio] protocol-native.c: Negotiated SHM: no                           
D: [pulseaudio] protocol-native.c: Disabling srbchannel, reason: No SHM support 
I: [pulseaudio] client.c: Freed 16 "supervisor"                                 
I: [pulseaudio] protocol-native.c: Connection died.                             
I: [pulseaudio] client.c: Created 17 "Native client (UNIX socket client)"       
I: [pulseaudio] protocol-native.c: Client authenticated anonymously.            
D: [pulseaudio] protocol-native.c: Protocol version: remote 33, local 33        
D: [pulseaudio] protocol-native.c: SHM possible: no                             
D: [pulseaudio] protocol-native.c: Negotiated SHM: no                           
D: [pulseaudio] protocol-native.c: Disabling srbchannel, reason: No SHM support 
I: [pulseaudio] client.c: Freed 17 "supervisor"                                 
I: [pulseaudio] protocol-native.c: Connection died.                             
I: [pulseaudio] client.c: Created 18 "Native client (UNIX socket client)"       
I: [pulseaudio] protocol-native.c: Client authenticated anonymously.            
D: [pulseaudio] protocol-native.c: Protocol version: remote 33, local 33
D: [pulseaudio] protocol-native.c: SHM possible: no
D: [pulseaudio] protocol-native.c: Negotiated SHM: no
D: [pulseaudio] protocol-native.c: Disabling srbchannel, reason: No SHM support
I: [pulseaudio] client.c: Freed 20 "supervisor"
I: [pulseaudio] protocol-native.c: Connection died.
I: [pulseaudio] client.c: Created 21 "Native client (UNIX socket client)"
I: [pulseaudio] protocol-native.c: Client authenticated anonymously.
D: [pulseaudio] protocol-native.c: Protocol version: remote 33, local 33
D: [pulseaudio] protocol-native.c: SHM possible: no
D: [pulseaudio] protocol-native.c: Negotiated SHM: no
D: [pulseaudio] protocol-native.c: Disabling srbchannel, reason: No SHM support
I: [pulseaudio] client.c: Freed 21 "supervisor"
I: [pulseaudio] protocol-native.c: Connection died.
I: [pulseaudio] client.c: Created 22 "Native client (UNIX socket client)"
I: [pulseaudio] protocol-native.c: Client authenticated anonymously.
D: [pulseaudio] protocol-native.c: Protocol version: remote 33, local 33
D: [pulseaudio] protocol-native.c: SHM possible: no
D: [pulseaudio] protocol-native.c: Negotiated SHM: no
D: [pulseaudio] protocol-native.c: Disabling srbchannel, reason: No SHM support
I: [pulseaudio] client.c: Freed 22 "supervisor"
I: [pulseaudio] protocol-native.c: Connection died.
I: [pulseaudio] client.c: Created 23 "Native client (UNIX socket client)"
I: [pulseaudio] protocol-native.c: Client authenticated anonymously.
D: [pulseaudio] protocol-native.c: Protocol version: remote 33, local 33
D: [pulseaudio] protocol-native.c: SHM possible: no
D: [pulseaudio] protocol-native.c: Negotiated SHM: no
D: [pulseaudio] protocol-native.c: Disabling srbchannel, reason: No SHM support
I: [pulseaudio] client.c: Freed 23 "supervisor"
I: [pulseaudio] protocol-native.c: Connection died.
I: [pulseaudio] client.c: Created 24 "Native client (UNIX socket client)"
I: [pulseaudio] protocol-native.c: Client authenticated anonymously.
D: [pulseaudio] protocol-native.c: Protocol version: remote 33, local 33
D: [pulseaudio] protocol-native.c: SHM possible: no
D: [pulseaudio] protocol-native.c: Negotiated SHM: no
D: [pulseaudio] protocol-native.c: Disabling srbchannel, reason: No SHM support
I: [pulseaudio] client.c: Freed 24 "supervisor"
I: [pulseaudio] protocol-native.c: Connection died.
```

**Comment by toMeloos** [comment]
Can confirm. Running the latest HA using HASS.io on a Raspberry Pi 4 and spotify sound broke after upgrades. It sounds corrupted, very noisy, not listenable.

**Comment by gnkarn** [comment]
using the same device with modipy and Spotify on a PI3  only Spotify generated sounds gets corrupted , all other  sound files i  sent from the modipy server ( on the same PI) to its sound output is played ok , in my case  the problem started with SU 209 . tks

**Comment by Med-WAHIB** [comment]
I have the same issue, I'm using the latest everything on Rpi 3.

**Comment by sblantipodi** [comment]
Don't ask me why but the latest updates fixed the problem for me

**Comment by toMeloos** [comment]
No improvement here either.

**Comment by Cloudenius** [comment]
Same issue here. Lots of folks are working from home due to COVID-19, so I'm really looking forward to use my receiver + 5.1 speakers again instead of my notebook speakers. :)

Let me know if anything is needed.

**Comment by Maco65** [comment]
Today, suddenly I have realised that I can select add-on from other Spotify apps. And when I turned on the amplifier - the sound was OK (amplifier was connected via additional USB sound card).
What I have done yesterday was adding one 1-wire temp sensor and for that RPi was turned off, sensor connected RPi turned on and then after adjusting configuration.yaml file HASS was restarted one or twice.

Today after this success I was so happy that I have removed my additional USB sound card and restarted system. Unfortunately then the sound was corrupted (not possible to listen) again. So I put the card again, restarted and the sound is OK.

So, partial success that:
* I can select device from other Spotify instances
* I can play normal sound on my additional USB sound card

Open issues remaining:
1) Audio devices listed on Supervisor/SYSTEM/HARDWARE have incorrect name: [object Object]
2) Sound from Spotify add-on is corrupted, distorted and not possible to listen

**Comment by sblantipodi** [comment]
having the same problem again after the update to 0.107.1
the strange things is that sometimes it works, sometimes it doesn't.

**Comment by sblantipodi** [comment]
it seems that selecting the correct audio output in the addon configuration
instead of the default one, works for me

(Built-in Audio Digital Stereo (IEC958)

**Comment by Med-WAHIB** [comment]
It worked for me after updating.

**Comment by sblantipodi** [comment]
> It worked for me after updating.

for me the update broke again but manually setting the audio output solved the problem

**Comment by Med-WAHIB** [comment]
> > It worked for me after updating.
> 
> for me the update broke again but manually setting the audio output solved the problem

I'm still on the 0.106.6 update, not sure if I want to update sins it is not working for you.

**Comment by toMeloos** [comment]
> having the same problem again after the update to 0.107.1
> 
> it seems that selecting the correct audio output in the addon configuration
> instead of the default one, works for me
> 
> (Built-in Audio Digital Stereo (IEC958)

This worked for me too. Only tested after upgrading, so on 0.107.1.

I'd call it a good workaround though. The "default" output device should work "out of the box".

**Comment by frenck** [comment]
Please note that the Home Assistant Core versions (and thus upgrades) are independent of the supervisor and audio containers. The version of core (e.g., 0.107.0/0.107.1/0.106.6/etc) has no influence on the audio. Hence reporting in status on upgrading core version, is kinda not helpful.

**Comment by toMeloos** [comment]
I can't speak for others, but just to be clear: I'm running the HASS.IO version, I'm experiencing this bug and that workaround by @sblantipodi works for me (at least on the latest version).

**Comment by Feryy** [comment]
It doesn't work for me.
I have the speakers connected to the jack. In Spotify Connect selected (Built-in Audio Digital Stereo (IEC958)
The sound is still broken.
Any setup in raspberry?

(raspberrypi4 HA version 0.108.1)

**Comment by Maco65** [comment]
I have changed Output to ``` Built-in Audio Digital Stereo (IEC958) ``` and it works !
I think I have done this test before and after restart the sound was corrupted again... Will test this later.
Still names of devices in configuration view are sort of strange... ``` [object Object] ```

**Comment by sblantipodi** [comment]
@toMeloos and @Maco65 nice that it worked for you.
thanks frenck for the aweome work here. 

in Italy the situation is "dramatic" and I hope you are all well there guys

**Comment by Maco65** [comment]
@frenck  
> The version of core (e.g., 0.107.0/0.107.1/0.106.6/etc) has no influence on the audio. Hence reporting in status on upgrading core version, is kinda not helpful.
Thanks frenck, I have realised this as during HASS restart Spotify player does not stop nor interrupt.
Excellent work with this Spotify Add-on !

@sblantipodi - keep well. We all wish the situation in Italy gets to normal as soon as possible !

**Comment by SasNst** [comment]
Same problem here.
Currently running hass.io version 0.107.5 on a RaspberryPi 3. Changing the audio output manually in the AddOn settings did not any effect in regards to the distortion. Running `speaker-test -c2 -t wav` worked fine, no distortion there. 
I also tried an external USB Soundcard, but could not get it to output any audio at all. 

Any further ideas would be appreciated

**Comment by Maco65** [comment]
This is weird... Today I have again experienced distortion with specific Output device selected in Add-on. I have then changed the Output to Default and the restarted Add-on. And... the sound is OK !
So for now, maybe workaround is to change the Output device (between Default and the other one) and Restart Add-on (maybe just Restart can work - anybody test it ?).
@frenck  if not core then what actually has influence on the audio from HA prospective ?

**Comment by Maco65** [comment]
@SasNst 
> 
> 
>
> I also tried an external USB Soundcard, but could not get it to output any audio at all.
>
Can you see external USB audio card in System/Hardware view ?
Or when you run terminal command ``` ha audio info ```  ?

**Comment by SasNst** [comment]
@Maco65 The card was visible in the System/Hardware view, but not in the output of `ha audio info`

Strangely, the issue seems to have resolved itself. I tried again today and it just worked without any further changes (output is set to Default). I tried restarting the Addon, as well as Home Assistang multiple times yesterday without any luck, so not sure what could cause this behaviour.

**Comment by Maco65** [comment]
Good it works and not so good that there is no clear reason why the issue appears/disappears :(
I think I had to REBOOT the system until I could use external USB card.

**Comment by Maco65** [comment]
Today again distortion :( This is what made it working (I have feeling this is very random...):
1. restart Add-on - no success
2. change Output to Default and restart Add-on - no success
3. change back to Deafult and restart - no success
4. Reboot the system - no success
5. restart Add-on - no success
6. change Output to Default and restart Add-on - SUCCESS !

**Comment by goffa72** [comment]
> Please note that the Home Assistant Core versions (and thus upgrades) are independent of the supervisor and audio containers. The version of core (e.g., 0.107.0/0.107.1/0.106.6/etc) has no influence on the audio. Hence reporting in status on upgrading core version, is kinda not helpful.

The addon started working again after updating to 0.107.3 but stopped working after getting the 0.107.7. This may not be helpful but its what happened. 
I've tried changing the output as suggested by Marc65 above and restarting but has not helped.

I might try rolling back to 0.107.3 and see if that gets it working again.

**Comment by Maco65** [comment]
I am confused as I am hearing that core version of HA does not have in influence on the audio. If this is true than those recent upgrades should not have any impact.
And in a way I can confirm it, yesterday none of the restarts, reboots and changing the Output did work for me - the sound was distorted in each case. Only adding external USB sound card helped and that card is working fine.
So,
1. where is the code responsible for sound ? Is it in "audio container" ?
2. Can this be downgraded ?
3. Where can I check the version (and history of upgrades) of it ?

**Comment by Maco65** [comment]
Few days ago I had another issue with HA on RPi4 (no connectivity at all) and as a result I have reinstalled all from scratch. And... the sound is correct both on default Add-on Output as well as on specific RPi audio ``` Built-in Audio Digital Stereo (IEC958) ```. So far is working.
Still the names of the Audio devices in Supervisor/SYSTEM/HARDWARE appears strangely as
```
    [object Object]
    [object Object]
    [object Object]
```
